version: '3'

services:
  frontend:
    image: marcussviniciusa/recantoverdev4-frontend:v1
    container_name: recantoverde-frontend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://apirecantoverde.marcussviniciusa.cloud
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recantoverde-frontend.entrypoints=websecure"
      - "traefik.http.routers.recantoverde-frontend.rule=Host(`recantoverde.marcussviniciusa.cloud`)"
      - "traefik.http.services.recantoverde-frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.recantoverde-frontend.middlewares=secureHeaders@file"

  backend:
    image: marcussviniciusa/recantoverdev4-backend:v8
    container_name: recantoverde-backend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:Marcus1911Marcus@206.183.131.10:27017/recanto_verdev3?authSource=admin
      - CLIENT_URL=https://recantoverde.marcussviniciusa.cloud
      - JWT_SECRET=wtwHLYfFxI9n1zDR8zFFqNq8kVaWqdD2oLpcjVmMBmedewewFWFWFw
      - WHATSAPP_API_DOMAIN=apigustavoamaral.marcussviniciusa.cloud
      - WHATSAPP_API_KEY=wtwHLYfFxI9n1zDR8zFFqNq8kVaWqdD2oLpcjVmMBm
      - WHATSAPP_INSTANCE=TesteAI
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recantoverde-backend.entrypoints=websecure"
      - "traefik.http.routers.recantoverde-backend.rule=Host(`apirecantoverde.marcussviniciusa.cloud`)"
      - "traefik.http.services.recantoverde-backend.loadbalancer.server.port=5000"
      - "traefik.http.routers.recantoverde-backend.middlewares=secureHeaders@file"

networks:
  proxy:
    external: true